services:

  app-test:

    build:
      context: .

      dockerfile: Dockerfile

      target: test

    container_name: todoapp-test
  
    command: ['npm', 'run', 'test:coverage']

    networks:
      - todoapp-network

    profiles:
      - test
